### ISSUE TITLE
[FEATURE]: Capital letter in BIDS dataset for sessions

### ISSUE THREAD

**Issue by Fayed-Rsl** [netstim/leaddbs#1154]
**Is your feature request related to a problem? Please describe.**
I have a BIDS dataset that looks like that:
![image](https://github.com/netstim/leaddbs/assets/84181583/e89fccec-6086-4144-ad62-b43bef8445a0)

This is pretty standard bids dataset and it is validated using bids validator.
But unfortunately when I use leaddbs it does not found the MRI for my subjects due to an error regarding the session naming.
Indeed, I noticed in the tutorial that there is only minor case for the session (highlighted in yellow)
![image](https://github.com/netstim/leaddbs/assets/84181583/0849ae75-76ed-4a0d-9068-db5c8a6c2f8a)

Unfortunately, as we can see from my bids dataset, my session naming is in CamelCase (e.g., **_PreOp_ vs _preop_**), so I guessed that was the reason why it didn't work. And it was in fact due to that. After renaming into minor case as in the tutorial everything worked fine.

This is why I think that having a feature that can recognise capital letter (e.g., PreOp considered as preop) could be a nice feature and I feel like it should not much be a lot complicated to implement. Otherwise, I would need to re-name my whole dataset to make leaddbs work.

Please let me know if this is possible to have such feature.
Thank you!
Fayed

**Comment by ningfei** [comment]
Thanks for the suggestion. Solved in 677eb38. Feel free to close the issue if it works for you.

**Comment by Fayed-Rsl** [comment]
> Thanks for the suggestion. Solved in [677eb38](https://github.com/netstim/leaddbs/commit/677eb3824ff8c9562e4aa5b0b5fce67f2a08b84d). Feel free to close the issue if it works for you.


Hi thank you for your quick reply.
I manage to make the update and I am currently using the leaddbs 3.1 version.
The fix you made is working well for parsing the filename including CamelCase, but for some reason I encountered an issue with the acquisition '_iso_' combined with CamelCase.

For example, this is working correctly:
_/BIDS/rawdata/sub-001/ses-PreOp/anat/sub-001_ses-PreOp_acq-ax_T1w.nii.gz_

But this is not working and leads to the error --> **Unrecognized field name 'acq'**
_/BIDS/rawdata/sub-001/ses-PreOp/anat/sub-001_ses-PreOp_acq-iso_T1w.nii.gz_

Note that if I rename the file as this (without camel case) then I have no error.
_/BIDS/rawdata/sub-001/ses-preop/anat/sub-001_ses-preop_acq-iso_T1w.nii.gz_


Could you please have a look into it?
Thank you!

**Comment by Fayed-Rsl** [comment]
> Thanks for the suggestion. Solved in 677eb38. Feel free to close the issue if it works for you.

Note that the solution proposed here also doesn't work for post operation CT files. For example: PostOp_CT still does not work but postop_CT works fine, indicating a problem in the fetching.

Thank you for your help
